services:
  - name: skct-result-bot
    type: worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    autoDeploy: true
    envVars:
      - key: 8249144005:AAHtUK9GHyG3Flkk0D1DMgYABw8_8faGgeg
        sync: false
      - key: 1436401249
        sync: false
      - key: hamsasanker06@gmail.com
        sync: false
      - key: ibyyouyptecnrbwa
        sync: false
      - key: hamsasanker06@gmail.com
        sync: false
      - key: 727823TUCS063
        sync: false
      - key: 09/03/2006
        sync: false
      - key: https://skct.edu.in/results/
        sync: false
